#------------------------------------------Cargo.toml------------------------------------------#

[workspace]
members = [
	'flicker',
	'rs_converters',
	'rs_scimatic'
]
resolver = '2'

[workspace.dependencies]
pyo3 = { version = '0.29.2', features = ['extension-module'] }

#------------------------------------------Th3Curs3dOn3------------------------------------------#
