#------------------------------------------pyproject.toml------------------------------------------#

[build-system]
requires = ['maturin>=1.0,<2.0']
build-backend = 'maturin'

[project]
name = 'SciMatic-Mobile'
version = '1.4.3'
description = 'A Python library for mathematics, science calculations, compter engineering concepts, and experimental mathematical functions.'
readme = 'README.md'
requires-python = '>=3.9'
license = { text = 'MIT' }
dependencies = [
    'platformdirs',
    'requests'
]

authors = [
    { name = 'TheCursedOne' }
]

[project.urls]
Repository = 'https://github.com/bingchiliingsacker-dot/SciMatic-Mobile'

[tool.maturin]
python-source = "."
module-name = "scimatic.rs_scimatic"
bindings = "pyo3"
manifest-path = "scimatic/Cargo.toml"
features = ["pyo3/extension-module"]
#------------------------------------------Th3Curs3dOn3------------------------------------------#
