#------------------------------------------pyproject.toml------------------------------------------#

[build-system]
requires = ['maturin>=1.0,<2.0']
build-backend = 'maturin'

[project]
name = 'SciMatic'
version = '1.32.1'
description = 'A Python library for mathematics, science calculations, compter engineering concepts, and experimental mathematical functions.'
readme = 'README.md'
requires-python = '>=3.9'
license = { text = 'MIT' }

authors = [
    { name = 'TheCursedOne' }
]

[project.urls]
Repository = 'https://github.com/bingchiliingsacker-dot/SciMatic'

[tool.maturin]
python-source = '.'
module-name = 'scimatic.flicker_module'
bindings = 'pyo3'

#------------------------------------------Th3Curs3dOn3------------------------------------------#
