#------------------------------------------Cargo.toml------------------------------------------#

[package]
name = 'flicker'
version = '1.0.2'
edition = '2021'

[lib]
name = 'flicker'
crate-type = ['cdylib']

[dependencies]
pyo3.workspace = true

#------------------------------------------Th3Curs3dOn3------------------------------------------#
