#------------------------------------------Cargo.toml------------------------------------------#

[package]
name = 'flicker_module'
version = '1.1.0'
edition = '2021'

[lib]
name = 'flicker_module'
crate-type = ['cdylib']

[dependencies]
pyo3.workspace = true

#------------------------------------------Th3Curs3dOn3------------------------------------------#
